In [2]:
import torch

*Legacy:* Tensor() mit großem T = Alias für torch.FloatTensor
Sie sollten stattdessen torch.tensor() verwenden, um Ihre Tensoren zu erstellen.

In [ ]:
# ============= Tensoren erstellen

# Nach der Größe 
w = torch.empty(100,200) 
w = torch.zeros(100,200) 
w = torch.ones(100,200)

# Nach Größe mit Zufallswerten 
w = torch.rand(100,200) 
w = torch.randn(100,200) 
w = torch.randint(5,10,(100,200)) # (low, high (size=tuple defining the shape))

# Mit angegebenem Datentyp oder Gerät initialisiert.
w = torch.empty((100,200), 
                dtype=torch.float64,
                device="cpu") #devide="cuda"

# Mit gleicher Größe, gleichem Datentyp und gleichem Gerät wie ein anderer Tensor initialisiert.
x = torch.empty_like(w)


In [ ]:
# ====== Tensorattribute

A = torch.tensor([[2,3],
                [4,5]])

print(".dtype: ", A.dtype)
print (".layout: ", A.layout)
print(".device: ", A.device)
print(".shape: ", A.shape)  # .size() und .shape ist das selbe!
print(".size(): ", A.size())
print(".ndim: ", A.ndim)

.dtype:  torch.int64
.layout:  torch.strided
.device:  cpu
.shape:  torch.Size([2, 2])
.size():  torch.Size([2, 2])
.ndim:  2


In [ ]:
# ==== Tensor indizieren
B = torch.tensor([[1,2],
                [3,4],
                [5,6]])
print(B)

# Indizierung: Gibt einen Tensor zurück!
print(B[0,1])

# Indizierung: gibt einen Wert als Python Zahl zurück
print(B[0,1].item())

# ===== Slicing
print (B[:2,0]) # :2 - EXKLUSIVE 2!

# ===== Boolesches Indizieren
print(B[B<5])

# === View (shares memory with original tensor!)



tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor(2)
2
tensor([1, 3])
tensor([1, 2, 3, 4])


In [37]:
# --- Iterate through Tensor
# 1D tensor: Vector

v = torch.randint(0,30,(3,))
print(v)
print(v.size())

v1 = torch.tensor([[1,2,3],
                  [4,5,6]])
print(v1.size())
print(v1.size(0))
print(v1.size(1))
# print(v1.shape(0)) doesnt work!


tensor([19, 10,  3])
torch.Size([3])
torch.Size([2, 3])
2
3


In [ ]:
A = torch.Tensor([[2,3],
                [4,5]])
a_storage = A.storage()
print("Storage:\n", a_storage)
print("Shape:\n ", A.shape)
print("View:\n ", A.view(1,4))

Storage:
  2.0
 3.0
 4.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 4]
Shape:
  torch.Size([2, 2])
View:
  tensor([[2., 3., 4., 5.]])


/var/folders/b_/13ns3vn128sfcpkm5ql4glyw0000gn/T/ipykernel_34031/1602509592.py:4: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a_storage = A.storage()


Storage = one-dimensional array of numerical data: a contiguous block of memory containing numbers of a given type
Tensor = view on storage

Offset = index in the storage corresponding to the first element in the tensor
Size/shape = tuple indicating how many elements across each dimension the tensor represents
Stride = the number of elements in the storage that need to be skipped over to
obtain the next element along each dimension

calling view on a tensor returns a new ten-
sor that changes the number of dimensions and the striding information, without
changing the storage.

In [3]:
torch.cuda.is_available()

False