In [2]:
import torch

*Legacy:* Tensor() mit großem T = Alias für torch.FloatTensor

-> stattdessen torch.tensor() verwenden

In [ ]:
# ============= Tensoren erstellen

# Nach der Größe 
w = torch.empty(100,200) 
w = torch.zeros(100,200) 
w = torch.ones(100,200)

# Nach Größe mit Zufallswerten 
w = torch.rand(100,200) 
w = torch.randn(100,200) 
w = torch.randint(5,10,(100,200)) # (low, high (size=tuple defining the shape))

# Mit angegebenem Datentyp oder Gerät initialisiert.
w = torch.empty((100,200), 
                dtype=torch.float64,
                device="cpu") #devide="cuda"

# Mit gleicher Größe, gleichem Datentyp und gleichem Gerät wie ein anderer Tensor initialisiert.
x = torch.empty_like(w)


In [ ]:
# ====== Tensorattribute

A = torch.tensor([[2,3],[4,5]])

print(".dtype: ", A.dtype)
print (".layout: ", A.layout)
print(".device: ", A.device)
print(".shape: ", A.shape)  # .size() und .shape ist das selbe!
print(".size(): ", A.size())
print(".ndim: ", A.ndim)

.dtype:  torch.int64
.layout:  torch.strided
.device:  cpu
.shape:  torch.Size([2, 2])
.size():  torch.Size([2, 2])
.ndim:  2


In [24]:
# ==== Tensor indizieren
B = torch.tensor([[1,2],
                [3,4],
                [5,6]])
print(B)

# Indizierung: Gibt einen Tensor zurück!
print(B[0,1])

# Indizierung: gibt einen Wert als Python Zahl zurück
print(B[0,1].item())

# ===== Slicing
print (B[:2,0]) # :2 - EXKLUSIVE 2!

# ===== Boolesches Indizieren
print(B[B<5])

# === View (shares memory with original tensor!)
print(B.view(6))


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor(2)
2
tensor([1, 3])
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4, 5, 6])


In [28]:
# ==== Durch Tensor iterieren
# 1D tensor: Vector

v = torch.randint(0,30,(3,))
print(v)

# for i in range(v.shape) FUNKTIONIERT NICHT; WEIL
# v.shape ist 'torch.Size' object, und er cannot be interpreted as an integer
# torch.Size is a subclass of "tuple" --> indexing the tupel for the size of 1D Tensor 
    
# Equivalent solutions: 
#for el in range(a.numel()):
#for el in range(a.size().numel()):
#for el in range(a.size(0)): #the size of 1st dimension = size of vector for 1D Tensor

for el in range(v.numel()):
        print(v[el])




tensor([27,  4, 20])
tensor(27)
tensor(4)
tensor(20)


 $$
\text{stride}[i] = \text{stride}[i+1] \times \text{size}[i+1]
$$

 
shape = (a, b, c)

- stride[2] = 1  (letzte Dimension) 
- stride[1] = c
- stride[0] = b * c

In [31]:
#####################
#w = torch.randint(5,10,(100,200)) # (low, high (size=tuple defining the shape))
t = torch.randint(1,20,(5,6,3))
print(t.size())
print(t.stride()) #18,3,1

torch.Size([5, 6, 3])
(18, 3, 1)


# Optional Task

Look up torch.permute and torch.reshape in the PyTorch documentation and experiment with them inside a new python file. Try to answer the following questions:

- How do .shape and .stride() change after a torch.permute or torch.reshape call? Does the underlying data move in memory?
- How does torch.reshape differ from torch.view?
- Why can reshaping a permuted tensor be handled differently than reshaping a freshly created tensor? *(Hint: check .is_contiguous() before and after torch.permute)*

**torch.permute(input, dims)**

Parameter:
- input (Tensor) – the input tensor.
- dims (torch.Size, tuple of int or list of int) – the desired ordering of dimensions.

**torch.reshape(input, dims)**

*Returns a tensor with the same data and number of elements as input, but with the specified shape.*

*When possible, the returned tensor will be a view of input. Otherwise, it will be a copy.*

Parameter:
- input (Tensor) – the tensor to be reshaped
- shape (tuple of int) – the new shape

In [ ]:
# RESHAPE: DATA DOESNT MOVE IN MEMORY!
# PERMUTE: DATA MOVES IN MEMORY

#https://pytorch-types.readthedocs.io/en/latest/

# A single dimension may be -1
b = torch.tensor([[0, 1], [2, 3],[4,5]])
b2 = torch.reshape(b, (-1,)) # to single dimension: -1
print(b.shape)
print(b.cpu(memory_format=torch.preserve_format) ) #Returns a copy of this object in CPU memory.

c = torch.permute(b, (1,0))
print(c)
print(c.cpu(memory_format=torch.preserve_format) )

print(b2.shape)
print(b2.cpu(memory_format=torch.preserve_format) )
print(b2.is_contiguous())

# .is_contiguous
# Returns True if self tensor is contiguous in memory 
# in the order specified by memory format

torch.Size([3, 2])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[0, 2, 4],
        [1, 3, 5]])
tensor([[0, 2, 4],
        [1, 3, 5]])
torch.Size([6])
tensor([0, 1, 2, 3, 4, 5])
True


In [29]:
# VIEW
#  zero-copy Operation —  zeigt auf denselben Speicher
# Returns a new tensor with the same data as the self tensor but of a different shape

# shares the same data and must have the same number of elements!

# reshape returns a view!
b = torch.tensor([[0, 1], [2, 3],[4,5]])
print(b)
print("Shape: ", b.shape) 
print("Stride: ", b.stride()) 
b2 = b.view(6)
print("\nView: flaches Array - b.view(6)")
print(b2)
print("Stride", b2.stride())




tensor([[0, 1],
        [2, 3],
        [4, 5]])
Shape:  torch.Size([3, 2])
Stride:  (2, 1)

View: flaches Array - b.view(6)
tensor([0, 1, 2, 3, 4, 5])
Stride (1,)


stride (1,)   # 1, weil Tuple mit einem Element, ohne , wäre es einfach eine Zahl

In [3]:
# torch.stride()

a = torch.tensor([[[1,2],[3,4]], [[5,6],[7,8]]])
print(a)
print(a.stride())
print(a.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
(4, 2, 1)
torch.Size([2, 2, 2])


In [ ]:
A = torch.Tensor([[2,3],
                [4,5]])
a_storage = A.storage()
print("Storage:\n", a_storage)
print("Shape:\n ", A.shape)
print("View:\n ", A.view(1,4))

Storage:
  2.0
 3.0
 4.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 4]
Shape:
  torch.Size([2, 2])
View:
  tensor([[2., 3., 4., 5.]])


/var/folders/b_/13ns3vn128sfcpkm5ql4glyw0000gn/T/ipykernel_34031/1602509592.py:4: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a_storage = A.storage()


Storage = one-dimensional array of numerical data: a contiguous block of memory containing numbers of a given type
Tensor = view on storage

Offset = index in the storage corresponding to the first element in the tensor
Size/shape = tuple indicating how many elements across each dimension the tensor represents
Stride = the number of elements in the storage that need to be skipped over to
obtain the next element along each dimension

calling view on a tensor returns a new ten-
sor that changes the number of dimensions and the striding information, without
changing the storage.

In [3]:
torch.cuda.is_available()

False